### ISSUE TITLE
Tuist generate

### ISSUE THREAD

**Issue by toanbv-fabbi** [HedvigInsurance/ugglan#1447]
I tried to use Tuist generate but received this error
![Screenshot 2024-08-14 at 11 24 02](https://github.com/user-attachments/assets/c8e31647-da6e-4cdf-93ff-6dd6c68f9be2)
Please help me

**Comment by sladan-hedvig** [comment]
In order to proceed with the build, you will need to have an access to the Hedvig private repositories. 
Unfortunately we are not able to help you with.

**Comment by sladan-hedvig** [comment]
We did some updates there and it should work now
